version: "3.8"

services:
  backend:
    image: flaviobuchmann/voting-backend:latest
    container_name: voting-app-backend
    ports:
      - "3001:3001"
    volumes:
      - voting-db:/app/data
    restart: unless-stopped

  frontend:
    image: flaviobuchmann/voting-frontend:latest
    container_name: voting-app-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-storage:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo '
        global:
          scrape_interval: 15s

        scrape_configs:
          - job_name: "prometheus"
            static_configs:
              - targets: ["localhost:9090"]

          - job_name: "cadvisor"
            static_configs:
              - targets: ["cadvisor:8080"]

          - job_name: "node-exporter"
            static_configs:
              - targets: ["node-exporter:9100"]

          - job_name: "voting-backend"
            static_configs:
              - targets: ["backend:3001"]
        ' > /etc/prometheus/prometheus.yml && exec /bin/prometheus --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped

volumes:
  voting-db:
  grafana-storage:
  prometheus-storage:
